name: Deploy to Production
on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'  

      - name: Install dependencies
        run: npm install  

      - name: Deploy to Heroku (example for Heroku)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: your-app-name
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku login -i
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git push heroku master
